version: "3.7"

services:
  postgres:
    container_name: "zika-postgres-db"
    image: "launchcodedevops/zika:geoserver"
    ports:
      - "5432:5432"
  geoserver:
    container_name: "zika-geoserver-api"
    image: "kartoza/geoserver:2.17.2"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - "./geoserver-config/data_dir/:/opt/geoserver/data_dir:rw"
      - "./geoserver-config/tomcat/web.xml:/usr/local/tomcat/conf/web.xml:rw"
